### PR TITLE
fix(phoneWidget): properly format phone numbers with hyphens and spaces

### LINKED ISSUE #105: [Dashboard] - Convert phone number with hyphens
## Expected Behavior
If Admin copies and pastes a phone number in a specific format, the system should recognize it and convert it to our own format. For instance, if admin plugs in “571-249- 5751” with hyphens, the system should know to auto-convert that to 571 249 5751 instead of “(571) 24-95”.

## Current Behavior
Currently, if you input “571-249- 5751” with hyphens, the system recognizes it as “(571) 24-95”, so user is forced to manually type in the rest.

## Steps to Reproduce (for bugs)
Note: The following steps are done in **PROD**
1. Go to a Reviews tab of any provider dashboard https://www.carelulu.com/dashboard/563797/reviews/list
2. Copy paste this number 571-249- 5751
3. You will see that the system saved (571) 24-95
image

## Context
We should make the system as smooth and easy to navigate as possible. Copying and pasting is what most admins and website users would do instead of typing in a phone number from scratch, so our system should recognize the various formats and convert it into our own.

## Your Environment
Using my PC, Chrome version Version 80.0.3987.87 (Official Build) (64-bit)

### PR DESCRIPTION
**Pull request by carelulu-jonathan**
**Summary**

If Admin copies and pastes a phone number in a specific format, the system should recognize it and convert it to our own format. For instance, if admin plugs in “571-249- 5751” with hyphens, the system should know to auto-convert that to 571 249 5751 instead of “(571) 24-95”.

This PR fixes/implements the following **bugs/features**

* [ ] Fix format of phone numbers if input have hyphens and/or spaces

**Test plan (required)**
1. Login as Admin
2. Go to `/dashboard/10/reviews/list`
3. Copy paste or type in `571-249- 5751`
4. It should return `(571) 249-5751` properly

**Code formatting**
NA

**Closing issues**
closes #105

### CODE REVIEW

File: src/utils.js [hunk 1]
```diff
@@ -392,7 +392,15 @@ const maskOptions = {
...
-  const text = (value === null || value === undefined) ? '' : `${value}`;
+  let text = (value === null || value === undefined) ? '' : `${value}`;
+
+  if (mask === '(999) 999-9999') {
+    if (text.indexOf('-') || text.indexOf(' ')) {
+      // remove hyphen and space characters
+      text = text.replace('-', '').replace(' ', '');
+    }
+  }
+
```
Comment (CareLuLu-Gabriel) [inline src/utils.js]: I like the idea of removing the characters before applying the mask but I think that shouldn't be placed here. Instead, lets add a third argument for maskFilter. The default filter can be:

```
const defaultParser = value => ((value === null || value === undefined) ? '' : `${value}`);

export const formatMask = (value, mask, maskParser) => {
  const parse = maskParser || defaultParser;
  let text = parse(value);
  // ...
}
```

We also need to change `TextInputWidget` to accept `maskParser` and change  `PhoneWidget` to send `maskParser`.

the parser can be a bit more general:
```
const maskParser = (value) => {
  const text = (value === null || value === undefined) ? '' : `${value}`;
  return text.replace(/[^0-9]/g, '');
};
```
